extends Resource

const PUZZLES := {
	3: ["r|gggg|bbbb|rrr|", "r|gggg|bbbb|rr|r", "rr|ggg|bbbb|rr|g", "rr|gggg|bbb|rr|b", "r|gggg|bbbb|r|rr", "rrr|gg|bbbb|r|gg", "rrr|gggg|bb|r|bb", "r|gggg|bbbb||rrr", "rr|ggg|bbbb|g|rr", "rr|gggg|bbb|b|rr", "rrr|gg|bbbb|gg|r", "rrr|gggg|bb|bb|r", "rrrr|g|bbbb|ggg|", "rrrr|g|bbbb|gg|g", "rrrr|gg|bbb|gg|b", "rrrr|g|bbbb|g|gg", "rrrr|ggg|bb|g|bb", "rrrr|g|bbbb||ggg", "rrrr|gg|bbb|b|gg", "rrrr|ggg|bb|bb|g"],
	4: ["|gggg|bbbb|rrrr|", "|gggg|bbbb|rrr|r", "r|ggg|bbbb|rrr|g", "r|gggg|bbb|rrr|b", "|gggg|bbbb|rr|rr", "rr|gg|bbbb|rr|gg", "rr|gggg|bb|rr|bb", "|gggg|bbbb|r|rrr", "rrr|g|bbbb|r|ggg", "rrr|gggg|b|r|bbb", "|gggg|bbbb||rrrr", "r|ggg|bbbb|g|rrr", "r|gggg|bbb|b|rrr", "rr|gg|bbbb|gg|rr", "rr|gggg|bb|bb|rr", "rrr|g|bbbb|ggg|r", "rrr|gggg|b|bbb|r", "rrrr||bbbb|gggg|", "rrrr||bbbb|ggg|g", "rrrr|g|bbb|ggg|b"],
	5: ["g|ggg|bbbb|rrrr|", "|ggg|bbbb|rrrr|g", "b|gggg|bbb|rrrr|", "|gggg|bbb|rrrr|b", "g|ggg|bbbb|rrr|r", "b|gggg|bbb|rrr|r", "r|gg|bbbb|rrr|gg", "r|gggg|bb|rrr|bb", "g|ggg|bbbb|rr|rr", "b|gggg|bbb|rr|rr", "rr|g|bbbb|rr|ggg", "rr|gggg|b|rr|bbb", "g|ggg|bbbb|r|rrr", "b|gggg|bbb|r|rrr", "rrr||bbbb|r|gggg", "rrr|gggg||r|bbbb", "g|ggg|bbbb||rrrr", "|ggg|bbbb|g|rrrr", "b|gggg|bbb||rrrr", "|gggg|bbb|b|rrrr"],
	6: ["gg|gg|bbbb|rrrr|", "g|gg|bbbb|rrrr|g", "g|ggg|bbb|rrrr|b", "|gg|bbbb|rrrr|gg", "b|ggg|bbb|rrrr|g", "bb|gggg|bb|rrrr|", "b|gggg|bb|rrrr|b", "|gggg|bb|rrrr|bb", "gg|gg|bbbb|rrr|r", "bb|gggg|bb|rrr|r", "r|g|bbbb|rrr|ggg", "r|gggg|b|rrr|bbb", "gg|gg|bbbb|rr|rr", "bb|gggg|bb|rr|rr", "rr||bbbb|rr|gggg", "rr|gggg||rr|bbbb", "gg|gg|bbbb|r|rrr", "bb|gggg|bb|r|rrr", "rr|r|bbbb|r|gggg", "rrr|b|bbb|r|gggg"],
	7: ["ggg|g|bbbb|rrrr|", "gg|g|bbbb|rrrr|g", "gg|gg|bbb|rrrr|b", "g|g|bbbb|rrrr|gg", "g|ggg|bb|rrrr|bb", "|g|bbbb|rrrr|ggg", "b|gg|bbb|rrrr|gg", "bb|ggg|bb|rrrr|g", "bbb|gggg|b|rrrr|", "bb|gggg|b|rrrr|b", "b|gggg|b|rrrr|bb", "|gggg|b|rrrr|bbb", "ggg|g|bbbb|rrr|r", "bbb|gggg|b|rrr|r", "r||bbbb|rrr|gggg", "r|gggg||rrr|bbbb", "ggg|g|bbbb|rr|rr", "bbb|gggg|b|rr|rr", "r|r|bbbb|rr|gggg", "rr|b|bbb|rr|gggg"],
	8: ["gggg||bbbb|rrrr|", "ggg||bbbb|rrrr|g", "ggg|g|bbb|rrrr|b", "gg||bbbb|rrrr|gg", "gg|gg|bb|rrrr|bb", "g||bbbb|rrrr|ggg", "g|ggg|b|rrrr|bbb", "||bbbb|rrrr|gggg", "b|g|bbb|rrrr|ggg", "bb|gg|bb|rrrr|gg", "bbb|ggg|b|rrrr|g", "bbbb|gggg||rrrr|", "bbb|gggg||rrrr|b", "bb|gggg||rrrr|bb", "b|gggg||rrrr|bbb", "|gggg||rrrr|bbbb", "gggg||bbbb|rrr|r", "bbbb|gggg||rrr|r", "|r|bbbb|rrr|gggg", "r|b|bbb|rrr|gggg"],
	9: ["gggg|b|bbb|rrrr|", "gggg||bbb|rrrr|b", "gggg|r|bbbb|rrr|", "ggg|b|bbb|rrrr|g", "ggg|r|bbbb|rrr|g", "ggg|g|bb|rrrr|bb", "gg|b|bbb|rrrr|gg", "gg|r|bbbb|rrr|gg", "gg|gg|b|rrrr|bbb", "g|b|bbb|rrrr|ggg", "g|r|bbbb|rrr|ggg", "g|ggg||rrrr|bbbb", "b||bbb|rrrr|gggg", "|b|bbb|rrrr|gggg", "bb|g|bb|rrrr|ggg", "bbb|gg|b|rrrr|gg", "bbbb|ggg||rrrr|g", "bbbb|ggg|g|rrrr|", "bbbb|gggg|r|rrr|", "bbb|ggg|g|rrrr|b"],
	10: ["gggg|bb|bb|rrrr|", "gggg|b|bb|rrrr|b", "gggg||bb|rrrr|bb", "gggg|r|bbb|rrr|b", "gggg|rr|bbbb|rr|", "ggg|bb|bb|rrrr|g", "ggg|rr|bbbb|rr|g", "ggg|g|b|rrrr|bbb", "gg|bb|bb|rrrr|gg", "gg|rr|bbbb|rr|gg", "gg|gg||rrrr|bbbb", "g|bb|bb|rrrr|ggg", "g|gg|g|rrrr|bbbb", "bb||bb|rrrr|gggg", "b|b|bb|rrrr|gggg", "|bb|bb|rrrr|gggg", "bbb|g|b|rrrr|ggg", "bbbb|gg||rrrr|gg", "bbbb|gg|g|rrrr|g", "bbbb|ggg|r|rrr|g"],
}